In [14]:
import numpy as np
import pandas as pd
import mat73 as mt
import matplotlib.pyplot as plt

from fppnpx.ChannelSignal import ChannelSignal

In [2]:
cpath = "/Users/mateouma/Downloads/monkey datasets/cluster_info_task.tsv"

ci = pd.read_csv(cpath, sep='\t')
ci = ci[ci['group'] == 'good']

In [3]:
ci

cluster_id  Amplitude  ContamPct KSLabel        amp   ch   depth  \
1             1       22.1        4.3    good  46.004280    2    40.0   
3             3        9.9        4.9    good  34.914692    0    20.0   
4             4       10.8        0.0    good  38.051731    3    40.0   
14           14       20.1        0.0    good  34.306488    6    80.0   
16           16       11.8       50.8     mua  27.166042    8   100.0   
..          ...        ...        ...     ...        ...  ...     ...   
552         583       12.1       63.6     mua  21.152679   46   480.0   
553         584       12.1       63.6     mua  21.152679   46   480.0   
554         585       11.3        4.1    good  32.800213  240  2420.0   
556         587       10.2       36.5     mua  16.257650  270  2720.0   
557         588       10.7        6.9    good  25.797224   68   700.0   

            fr group  n_spikes   sh  
1     0.562448  good      3923  0.0  
3     0.475565  good      3317  0.0  
4     0.427249  good      2980  0.0  
14    2.188430  good     15264  0.0  
16    1.013927  good      7072  0.0  
..         ...   ...       ...  ...  
552   7.609038  good     53072  0.0  
553   0.413341  good      2883  0.0  
554   6.564000  good     45783  0.0  
556  12.742615  good     88878  0.0  
557  18.887395  good    131737  0.0  

[239 rows x 11 columns]

In [ ]:
ci[ci['ch'] == 13]

cluster_id  Amplitude  ContamPct KSLabel        amp  ch  depth        fr  \
20          20       24.3        0.0    good  43.376743  13  140.0  0.788403   
21          21       21.6        4.4    good  54.743973  13  140.0  4.160368   

   group  n_spikes   sh  
20  good      5499  0.0  
21  good     29018  0.0

In [178]:
wfpath = "/Users/mateouma/Downloads/monkey datasets/20230630_DLPFCwaveforms.mat"
wf = mt.loadmat(wfpath)['goodUnits']

In [182]:
wf_gu_channels = np.array(wf['channelId'], dtype=int)
wf_gu_channels

array([ 15,  13,  14,  17,  23,  25,  25,  30,  38,  36,  46,  50,  52,
        55,  56,  62,  65,  67,  64,  70,  70,  71,  76,  73,  73,  72,
        77,  89, 120, 122, 132, 135, 136, 136, 140, 142, 144, 140, 141,
       148, 145, 146, 145, 150, 151, 148, 155, 156, 154, 152, 156, 162,
       160, 160, 160, 163, 166, 166, 168, 168, 169, 171, 172, 175, 172,
       177, 177, 177, 180, 181, 183, 182, 186, 184, 188, 189, 190, 188,
       188, 192, 195, 198, 198, 200, 205, 205, 208, 208, 209, 212, 216,
       219, 221, 221, 220, 221, 224, 226, 230, 228, 234, 232, 236, 237,
       240, 244, 246, 248, 252, 254, 258, 260, 278, 280, 282, 287, 298,
       302, 304, 309, 335, 336, 350, 352, 357, 356, 363, 368, 382, 176,
       201, 340, 204, 190, 142,  46, 240, 270])

In [8]:
pd.DataFrame(wf)

Amplitude          amp channelId  cluId  \
0        25.4  50.22740173      15.0   17.0   
1        21.6  54.74397278      13.0   21.0   
2        10.6  18.55448532      14.0   22.0   
3        10.6   36.6762352      17.0   24.0   
4        13.5  27.39281845      23.0   35.0   
..        ...          ...       ...    ...   
133      12.3  77.51120758     190.0  561.0   
134      17.2  47.46772766     142.0  572.0   
135      12.1  21.15267944      46.0  583.0   
136      11.3  32.80021286     240.0  585.0   
137      10.2  16.25765038     270.0  587.0   

                                     cluster_waveforms  \
0    [[219.62215, nan], [228.13664, nan], [234.9485...   
1    [[92.525246, nan], [90.372826, nan], [89.44674...   
2    [[39.70659, nan], [40.663662, nan], [41.493668...   
3    [[13.226153, nan], [13.798254, nan], [14.44009...   
4    [[68.37215, nan], [70.906334, nan], [73.678566...   
..                                                 ...   
133  [[56.85442, nan], [50.638214, nan], [42.989574...   
134  [[79.66124, 67.36857], [78.879005, 62.679268],...   
135  [[58.819016, nan], [61.90513, nan], [64.95043,...   
136  [[-1.4172093, nan], [-2.5794165, nan], [-3.103...   
137  [[40.43777, 44.53967], [42.191303, 46.508144],...   

                       cluster_waveforms_time_relative   depth           fr  \
0    [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...   160.0   5.35551717   
1    [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...   140.0    4.1603683   
2    [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...   160.0   3.77656149   
3    [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...   180.0   2.10541762   
4    [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...   240.0   2.65066128   
..                                                 ...     ...          ...   
133  [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...  1920.0  23.26798301   
134  [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...  1440.0   9.99130697   
135  [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...   480.0   7.60903805   
136  [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...  2420.0   6.56399964   
137  [-29, -28, -27, -26, -25, -24, -23, -22, -21, ...  2720.0  12.74261539   

     n_spikes                                                 st  \
0     37354.0  [5033, 26765, 70175, 106570, 121640, 126151, 1...   
1     29018.0  [1796, 4074, 7332, 21257, 32415, 35589, 43363,...   
2     26341.0  [151325, 151541, 192515, 204290, 240637, 31598...   
3     14685.0  [45032, 55678, 68686, 126955, 128280, 135318, ...   
4     18488.0  [228419, 317578, 372853, 374187, 374309, 37448...   
..        ...                                                ...   
133  162291.0  [191, 1122, 2500, 3189, 3513, 5141, 5895, 7311...   
134   69688.0  [40859, 41216, 46432, 48830, 56088, 56697, 118...   
135   53072.0  [54117, 128933, 129983, 132846, 132969, 141183...   
136   45783.0  [480795, 701649, 908754, 1592328, 1680816, 205...   
137   88878.0  [2053, 8820, 9845, 10279, 21948, 22859, 23081,...   

    waveformTimeRelative                                          waveforms  
0          [-20.0, 41.0]  [[6, 0, 4, -5, -4, 2, 4, -4, 0, 2, 10, -4, -2,...  
1          [-20.0, 41.0]  [[3, -2, 1, -1, 4, 9, -2, 3, 6, 1, 0, 6, 3, 2,...  
2          [-20.0, 41.0]  [[-5, 5, 1, 1, 1, -2, 4, -4, -2, -3, -4, -9, 4...  
3          [-20.0, 41.0]  [[1, -7, -2, 3, 10, 0, -1, -5, -1, 8, 0, 1, 1,...  
4          [-20.0, 41.0]  [[-2, 4, 0, 3, 0, 3, 2, 3, 7, -9, 3, -2, 2, -1...  
..                   ...                                                ...  
133        [-20.0, 41.0]  [[-7, -2, -1, -5, -11, -7, -2, -7, 10, 6, 4, 5...  
134        [-20.0, 41.0]  [[-12, 7, -3, 1, 0, 0, -8, 1, 5, 0, 1, 9, 1, -...  
135        [-20.0, 41.0]  [[3, -2, 4, 0, 3, -5, 1, -4, 9, 6, -1, -3, 4, ...  
136        [-20.0, 41.0]  [[-2, -5, -6, 2, 0, -12, -7, 2, -2, -8, 1, -5,...  
137        [-20.0, 41.0]  [[0, 3, 9, -2, 4, 1, 7, -2, 4, -1, 0, 2, 6, 2,...  

[138 rows x 12 columns]

In [1]:
import numpy as np

In [60]:
spk_clusters = np.load("/Users/mateouma/Downloads/tibs_chkdelay_0630/spike_clusters.npy")

spk_clusters.shape

(15907387,)

In [ ]:
# THERE IS NO CHANNEL 191 (0-indexed)

chan_map = np.load("/Users/mateouma/Downloads/tibs_chkdelay_0630/channel_map.npy")

In [61]:
testpath = "/Users/mateouma/Downloads/tibs_chkdelay_0630/templates.npy"

templates = np.load(testpath)
templates.shape

(551, 61, 383)

In [63]:
spk_template_path = "/Users/mateouma/Downloads/tibs_chkdelay_0630/spike_templates.npy"

spk_templates = np.load(spk_template_path)
spk_templates.shape

(15907387,)

In [153]:
np.where(spk_clusters != spk_templates)

(array([       0,        8,       14, ..., 15907350, 15907377, 15907383]),)

In [154]:
spk_clusters[0], spk_templates[0]

(570, 318)

In [116]:
cpath = "/Users/mateouma/Downloads/monkey datasets/cluster_info_task.tsv"

ci = pd.read_csv(cpath, sep='\t')
cig = ci[ci['group'] == 'good']

In [119]:
np.unique(cig['ch'].values)

array([  0,   2,   3,   6,   8,  13,  14,  15,  17,  19,  20,  21,  23,
        25,  26,  27,  28,  30,  35,  36,  37,  38,  42,  43,  44,  46,
        47,  50,  51,  52,  54,  55,  56,  57,  58,  60,  61,  62,  64,
        65,  67,  68,  70,  71,  72,  73,  76,  77,  78,  80,  82,  83,
        89, 116, 120, 122, 123, 124, 127, 129, 132, 133, 134, 135, 136,
       138, 140, 141, 142, 144, 145, 146, 148, 150, 151, 152, 154, 155,
       156, 159, 160, 161, 162, 163, 164, 165, 166, 168, 169, 171, 172,
       174, 175, 176, 177, 178, 180, 181, 182, 183, 184, 186, 188, 189,
       190, 192, 193, 195, 196, 198, 200, 201, 204, 205, 208, 209, 212,
       214, 216, 217, 219, 220, 221, 224, 226, 228, 229, 230, 231, 232,
       234, 236, 237, 238, 240, 244, 246, 247, 248, 252, 254, 258, 260,
       262, 270, 275, 276, 278, 279, 280, 282, 284, 286, 287, 290, 294,
       298, 302, 304, 308, 309, 318, 335, 336, 340, 350, 352, 356, 357,
       363, 368, 382])

In [155]:
np.unique(cig['cluster_id'].values)

array([  1,   3,   4,  14,  16,  17,  20,  21,  22,  24,  26,  31,  33,
        35,  36,  39,  41,  42,  47,  48,  52,  54,  58,  61,  64,  65,
        66,  68,  72,  73,  77,  79,  80,  84,  87,  91,  94,  95,  97,
       101, 103, 105, 106, 107, 108, 110, 111, 112, 113, 114, 116, 117,
       119, 123, 125, 127, 129, 130, 132, 135, 136, 139, 140, 142, 146,
       149, 150, 153, 154, 155, 157, 158, 161, 163, 164, 165, 177, 206,
       212, 213, 215, 217, 218, 226, 227, 230, 231, 234, 235, 239, 240,
       241, 242, 243, 247, 248, 249, 250, 251, 255, 257, 258, 260, 262,
       263, 265, 268, 269, 272, 274, 275, 278, 282, 284, 285, 286, 287,
       291, 292, 294, 295, 296, 297, 298, 306, 310, 311, 313, 314, 315,
       316, 317, 322, 323, 324, 328, 329, 332, 333, 335, 336, 339, 340,
       341, 343, 344, 346, 347, 348, 350, 353, 354, 356, 359, 360, 362,
       365, 368, 372, 374, 375, 377, 378, 379, 380, 381, 383, 387, 389,
       392, 393, 396, 397, 398, 400, 401, 403, 405, 406, 409, 41

In [124]:
template_amps = np.max(np.abs(templates), axis=1) # maximum amplitude of each template on each channel
template_amps.shape

(551, 383)

In [263]:
sort_template_to_clust = {t:c for t,c in zip(spk_templates, spk_clusters)}

In [238]:
chan_temps = []
templates_on_chan_list = []

amp_thres = 0

for i,chan in enumerate(chan_map):
    templates_on_chan = np.where(template_amps[:,i] > amp_thres)[0]
    templates_on_chan_list.append(templates_on_chan)
    chan_temps.append(len(templates_on_chan))

    print('Channel', chan)
    print(templates_on_chan) # template indices that are located on channel i

Channel 0
[0 1 2 3 4 5 7]
Channel 1
[0 1 2 3 4 5 7]
Channel 2
[0 1 2 3 4 5 6 7 8]
Channel 3
[0 1 2 3 4 5 6 7 8]
Channel 4
[ 0  1  2  3  4  5  6  7  8  9 11 13 14 15 16]
Channel 5
[ 0  1  2  3  4  5  6  7  8  9 11 13 14 15 16]
Channel 6
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Channel 7
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Channel 8
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 20 21 22 23]
Channel 9
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 20 21 22 23]
Channel 10
[ 6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Channel 11
[ 6  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Channel 12
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 27]
Channel 13
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 27]
Channel 14
[ 9 10 11 12 14 15 17 18 19 20 21 22 23 24 25 26 27 28]
Channel 15
[ 9 10 11 12 14 15 17 18 19 20 21 22 23 24 25 26 27 28]
Channel 16
[17 18 19 20 21 22 23 24 25 26 27 28 29 31 32 33 34 35 36]
Channel 17
[17 18 19 20 21 22 23

In [227]:
units_inuse = np.array(wf['cluId'], dtype='int')
units_inuse

array([ 17,  21,  22,  24,  35,  41,  48,  52,  64,  65,  80,  87,  91,
        95, 105, 116, 117, 123, 125, 129, 130, 135, 139, 140, 146, 150,
       153, 177, 213, 215, 227, 234, 239, 241, 247, 248, 249, 250, 251,
       255, 257, 260, 263, 265, 268, 269, 272, 274, 275, 278, 284, 286,
       287, 291, 292, 296, 298, 306, 310, 311, 313, 314, 315, 317, 322,
       323, 328, 329, 332, 333, 335, 336, 339, 340, 344, 346, 347, 348,
       350, 354, 356, 360, 362, 365, 374, 375, 378, 379, 380, 383, 389,
       392, 393, 396, 397, 398, 401, 403, 405, 410, 417, 418, 419, 423,
       429, 433, 435, 439, 441, 443, 447, 449, 469, 470, 473, 480, 491,
       496, 500, 502, 516, 519, 523, 526, 528, 530, 531, 539, 548, 552,
       554, 556, 557, 561, 572, 583, 585, 587])

In [ ]:
chan_template_dict = {}
chan_unit_dict_uiu = {} # the units we're using

for wgc in wf_gu_channels:
    chan_idx = np.where(chan_map == wgc)[0][0]

    sorted_templates = [sort_template_to_clust.get(tmp) for tmp in templates_on_chan_list[chan_idx]]

    chan_template_dict[f'ch{wgc}'] = templates_on_chan_list[chan_idx]
    chan_unit_dict_uiu[f'ch{wgc}'] = np.intersect1d(units_inuse, sorted_templates)

In [268]:
chan_template_dict

{'ch15': array([ 9, 10, 11, 12, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28]),
 'ch13': array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 27]),
 'ch14': array([ 9, 10, 11, 12, 14, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28]),
 'ch17': array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34,
        35, 36]),
 'ch23': array([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48]),
 'ch25': array([29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 51, 54, 55]),
 'ch30': array([37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60]),
 'ch38': array([56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73]),
 'ch36': array([56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]),
 'ch46': array([69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85

In [267]:
chan_unit_dict_uiu

{'ch15': array([17, 21, 22, 24]),
 'ch13': array([17, 21, 22, 24]),
 'ch14': array([17, 21, 22, 24]),
 'ch17': array([17, 21, 22, 24, 35]),
 'ch23': array([24, 35, 41, 48]),
 'ch25': array([35, 41, 48]),
 'ch30': array([41, 48, 52]),
 'ch38': array([64, 65]),
 'ch36': array([64, 65]),
 'ch46': array([ 80,  87, 583]),
 'ch50': array([ 80,  87,  91,  95, 583]),
 'ch52': array([ 87,  91,  95, 105]),
 'ch55': array([ 87,  91,  95, 105]),
 'ch56': array([ 91,  95, 105, 116]),
 'ch62': array([105, 116, 117, 123, 125]),
 'ch65': array([116, 117, 123, 125]),
 'ch67': array([116, 117, 123, 125, 129, 130, 135]),
 'ch64': array([116, 117, 123, 125]),
 'ch70': array([117, 123, 125, 129, 130, 135, 139, 140, 146, 150]),
 'ch71': array([117, 123, 125, 129, 130, 135, 139, 140, 146, 150]),
 'ch76': array([139, 140, 146, 150, 153]),
 'ch73': array([129, 130, 135, 139, 140, 146, 150, 153]),
 'ch72': array([129, 130, 135, 139, 140, 146, 150, 153]),
 'ch77': array([139, 140, 146, 150, 153]),
 'ch89': array